import { RequestHandler } from "express";

type GenerateWebsiteBody = {
  brandName?: string;
  tagline?: string;
  primaryColor?: string;
  accentColor?: string;
};

function safe(s: string | undefined, fallback: string) {
  const v = (s || "").trim();
  return v || fallback;
}

/**
 * Simple website generator that returns a small static site template.
 *
 * This is intentionally NOT "AI-heavy" so the app works without keys.
 */
export const handleGenerateWebsite: RequestHandler = async (req, res) => {
  const body = (req.body || {}) as GenerateWebsiteBody;
  const brandName = safe(body.brandName, "Launchly Site");
  const tagline = safe(body.tagline, "Start faster. Grow smarter. Monetize everything.");
  const primary = safe(body.primaryColor, "#7C3AED");
  const accent = safe(body.accentColor, "#6EE7B7");

  const indexHtml = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>${brandName}</title>
  <link rel="stylesheet" href="styles.css" />
</head>
<body>
  <header class="nav">
    <div class="container nav-inner">
      <div class="brand">${brandName}</div>
      <nav class="links">
        <a href="#features">Features</a>
        <a href="#pricing">Pricing</a>
        <a class="btn" href="#cta">Get Started</a>
      </nav>
    </div>
  </header>

  <main>
    <section class="hero">
      <div class="container hero-inner">
        <h1>${tagline}</h1>
        <p>High-quality landing page generated by Launchly. Replace text, connect Stripe, and deploy.</p>
        <div class="hero-actions">
          <a class="btn" href="#cta">Start now</a>
          <a class="btn ghost" href="#features">See features</a>
        </div>
      </div>
      <div class="glow"></div>
    </section>

    <section id="features" class="section">
      <div class="container grid">
        <div class="card">
          <h3>Checkout-ready</h3>
          <p>Add your Stripe payment link or Stripe Checkout page.</p>
        </div>
        <div class="card">
          <h3>Fast & responsive</h3>
          <p>Mobile-first layout with a modern glass/neon style.</p>
        </div>
        <div class="card">
          <h3>Deploy in minutes</h3>
          <p>Deploy to Netlify, Vercel, or Firebase Hosting.</p>
        </div>
      </div>
    </section>

    <section id="pricing" class="section">
      <div class="container pricing">
        <div class="price">
          <h3>Starter</h3>
          <div class="amount">$19<span>/mo</span></div>
          <ul>
            <li>Landing page</li>
            <li>Stripe link</li>
            <li>Email capture</li>
          </ul>
        </div>
        <div class="price featured">
          <h3>Pro</h3>
          <div class="amount">$49<span>/mo</span></div>
          <ul>
            <li>Full site</li>
            <li>Payments + upsells</li>
            <li>Analytics</li>
          </ul>
        </div>
        <div class="price">
          <h3>Growth</h3>
          <div class="amount">$99<span>/mo</span></div>
          <ul>
            <li>Funnels</li>
            <li>Ads-ready assets</li>
            <li>Automation</li>
          </ul>
        </div>
      </div>
    </section>

    <section id="cta" class="section">
      <div class="container cta">
        <div>
          <h2>Ready to launch?</h2>
          <p>Paste your Stripe payment link below and you're live.</p>
        </div>
        <form class="cta-form" onsubmit="event.preventDefault(); alert('Replace this with Stripe Checkout link logic.');">
          <input placeholder="Stripe payment link or checkout URL" />
          <button class="btn" type="submit">Save</button>
        </form>
      </div>
    </section>
  </main>

  <footer class="footer">
    <div class="container">© ${new Date().getFullYear()} ${brandName}</div>
  </footer>
</body>
</html>`;

  const stylesCss = `:root{--primary:${primary};--accent:${accent};--bg:#050914;--card:rgba(255,255,255,.05);--border:rgba(255,255,255,.08);--text:#e7eefc;--muted:#9fb0d0}
*{box-sizing:border-box}body{margin:0;font-family:ui-sans-serif,system-ui,-apple-system,Segoe UI,Roboto,Inter,Arial;background:radial-gradient(1200px 700px at 20% -10%,rgba(124,58,237,.35),transparent 55%),radial-gradient(900px 600px at 90% 10%,rgba(110,231,183,.2),transparent 50%),var(--bg);color:var(--text)}
a{color:inherit;text-decoration:none;opacity:.9}a:hover{opacity:1}
.container{width:min(1100px,92%);margin:0 auto}
.nav{position:sticky;top:0;backdrop-filter:blur(10px);background:rgba(0,0,0,.25);border-bottom:1px solid var(--border);z-index:10}
.nav-inner{display:flex;align-items:center;justify-content:space-between;padding:14px 0}
.brand{font-weight:800;letter-spacing:.2px}
.links{display:flex;gap:14px;align-items:center}
.btn{display:inline-flex;align-items:center;justify-content:center;padding:10px 14px;border-radius:12px;border:1px solid var(--border);background:linear-gradient(180deg,rgba(255,255,255,.06),rgba(255,255,255,.03));box-shadow:0 0 0 1px rgba(0,0,0,.15) inset}
.btn:hover{border-color:rgba(255,255,255,.16)}
.btn.ghost{background:transparent}
.hero{position:relative;padding:84px 0 48px;overflow:hidden}
.hero-inner{position:relative;z-index:2}
.hero h1{font-size:clamp(34px,5vw,56px);line-height:1.05;margin:0 0 12px}
.hero p{color:var(--muted);max-width:60ch;margin:0 0 18px}
.hero-actions{display:flex;gap:10px;flex-wrap:wrap}
.glow{position:absolute;inset:-120px;pointer-events:none;background:radial-gradient(600px 300px at 30% 30%,rgba(124,58,237,.22),transparent 60%),radial-gradient(520px 260px at 70% 40%,rgba(110,231,183,.14),transparent 65%)}
.section{padding:44px 0}
.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}
.card{padding:18px;border-radius:16px;background:var(--card);border:1px solid var(--border);backdrop-filter:blur(10px)}
.pricing{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}
.price{padding:18px;border-radius:16px;background:var(--card);border:1px solid var(--border)}
.price.featured{border-color:rgba(124,58,237,.5);box-shadow:0 0 40px rgba(124,58,237,.18)}
.amount{font-size:34px;font-weight:800;margin:10px 0 12px}
.amount span{font-size:14px;color:var(--muted);font-weight:600}
ul{margin:0;padding-left:18px;color:var(--muted)}
.cta{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:18px;border:1px solid rgba(124,58,237,.35);background:rgba(124,58,237,.08);border-radius:18px}
.cta-form{display:flex;gap:10px;flex-wrap:wrap}
.cta input{min-width:280px;flex:1;padding:10px 12px;border-radius:12px;border:1px solid var(--border);background:rgba(0,0,0,.25);color:var(--text)}
.footer{padding:26px 0;color:var(--muted);border-top:1px solid var(--border)}
@media (max-width:860px){.grid,.pricing{grid-template-columns:1fr}.links{display:none}.cta{flex-direction:column;align-items:flex-start}.cta input{min-width:100%}}
`;

  res.json({
    success: true,
    template: "static-html",
    files: [
      { path: "index.html", content: indexHtml },
      { path: "styles.css", content: stylesCss },
      {
        path: "README.txt",
        content:
          "Deploy: upload these files to Netlify/Vercel/Firebase Hosting.\nStripe: replace the CTA form with your Stripe Payment Link or Checkout Session redirect.",
      },
    ],
  });
};
